[package]
name = "bincode-targets"
version = "0.0.0"
publish = false

[dependencies]
bincode = { git = "https://github.com/TyOverby/bincode" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

[[bin]]
name = "read_bytes"
path = "read_bytes.rs"
